name: Sync GitHub Issues to Azure DevOps Work Items

on:
  issues:
    types:
      - labeled
  issue_comment:
    types:
      - created
      - edited

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

permissions:
  id-token: write
  issues: write
  contents: read

jobs:
  updateAzDO:
    if: github.event.label.name == 'sprint'
    runs-on: ubuntu-latest
    environment: azurecloud

    steps:
      # Step 1: Login to Azure using federated identity
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ENTRA_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.ENTRA_APP_TENANT_ID }}
          subscription-id: ${{ secrets.ADO_SUBSCRIPTION_ID }}
          environment: azurecloud
          # allow-no-subscriptions: true
          # enable-debug-logs: true

      # Step 2: Obtain Azure DevOps token
      - name: Get Azure DevOps token
        id: get_ado_token
        run: |
          # Fetch Azure DevOps token using resource ID 499b84ac-1321-427f-aa17-267ca6975798
          ado_token=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv)
          echo "ado_token=${ado_token}" >> $GITHUB_ENV

      # Step 3: Sync GitHub issue to Azure DevOps work item
      - name: Sync issue to Azure DevOps
        uses: pavelhorak/github-actions-issue-to-work-item@main
        env:
          ado_token: "${{ env.ado_token }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ secrets.ADO_ORGANIZATION }}"
          ado_project: "${{ secrets.ADO_PROJECT }}"
          ado_area_path: "${{ secrets.ADO_AREA_PATH }}"
          ado_iteration_path: "${{ secrets.ADO_ITERATION_PATH }}"
          ado_wit: "User Story" # Work Item Type
          ado_new_state: "Committed"
          ado_active_state: "In Progress"
          ado_close_state: "Completed"
          ado_bypassrules: false
